educa/urls.py
from django.contrib import admin
from django.urls import include, path

from django.conf import settings
from django.conf.urls.static import static

from django.contrib.auth import views as auth_views

urlpatterns = [
    path("accounts/login/", auth_views.LoginView.as_view(), name="login"),
    path("accounts/logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("admin/", admin.site.urls),
    path("course/", include("courses.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

modules/urls.py
from django.urls import path
from .views import (
    manage_module_list_view,
    module_list_view,
    module_detail_view,
    module_create_view,
    module_update_view,
    module_delete_view,
    topic_update_view,
    resource_list_view,
    resource_create_view,
    resource_delete_view
)

app_name = 'modules'

urlpatterns = [
    # Order: View > Create > Update > Delete
    # Modules
    path('dashboard/', manage_module_list_view, name='manage_list'),
    path('all/', module_list_view, name='list'),
    path('create/', module_create_view, name='create'),
    path('edit/<int:pk>/', module_update_view, name='edit'),
    path('delete/<int:pk>/', module_delete_view, name='delete'),
    path('<slug:slug>/', module_detail_view, name='detail'),

    # Topics
    path('topic/<int:pk>/edit/', topic_update_view, name='topic_update'),

    # Resources
    path('topic/<int:topic_id>/', resource_list_view, name='resource_list'),
    path('topic/<int:topic_id>/resource/<model_name>/create/',
         resource_create_view, name='resource_create'),
    path('topic/<int:topic_id>/resource/<model_name>/<id>/',
         resource_create_view, name='resource_update'),
    path('resource/<int:id>/delete/', resource_delete_view,
         name='resource_delete'),
]

moodle/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from django.views.generic.base import TemplateView
from modules.views import ModuleListView

# from django.contrib.auth import views as auth_views

urlpatterns = [
    # path('accounts/login/', auth_views.LoginView.as_view(), name='login'),
    # path('accounts/logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('admin/', admin.site.urls),
    path('tinymce/', include('tinymce.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
    path('students/', include('students.urls')),
    path('modules/', include('modules.urls')), ]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <title>{% block title %}{% endblock title %}</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
    integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
  <!-- FONTAWESOME -->
  <script src="https://kit.fontawesome.com/7f388aaeba.js" crossorigin="anonymous"></script>
</head>

<body>
  {% include 'navbar.html' %}
  <main>
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-8">
          <hr class="mt-0 mb-4">

          {% if messages %}
          <div class="alert alert-success">
            {% for message in messages %}
            {{ message|safe }}
            {% endfor %}
          </div>
          {% endif %}

          {% block content %}

          {% endblock %}
        </div>
      </div>
    </div>
  </main>


  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
    integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
    integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
    crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
    integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI"
    crossorigin="anonymous"></script>
</body>

</html>

templates/home.html
{% extends 'base.html' %}

{% block title %}Home{% endblock title %}

{% block content %}
{% if user.is_authenticated %}
  Hi, {{ user.first_name }}!
  <p><a href="{% url 'logout' %}">Log Out</a></p>
{% else %}
  <p>You are not logged in</p>
  <a href="{% url 'login' %}">Log In</a> |
  <a href="{% url 'signup' %}">Sign Up</a>
{% endif %}
{% endblock content %}

templates/navbar.html
<!-- NAVIGATION BAR -->
<nav class="navbar navbar-expand-sm bg-dark navbar-dark">
    <a class="navbar-brand" href="">moodle</a>
    {% if user.is_authenticated %}
    <ul class="navbar-nav">
        <!-- Dropdown -->
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="" id="navbardrop" data-toggle="dropdown">
                My Modules
            </a>
            <div class="dropdown-menu">
                <a class="dropdown-item"
                    href="{% if request.user.is_staff %}{% url 'modules:manage_list' %}{% endif %}">All</a>
                {% for module in modules %}
                <a class="dropdown-item" href="{% url 'modules:detail' module.slug %}">{{ module.title }}</a>
                {% endfor %}
            </div>
        </li>

        <li class="nav-item dropdown">
            <a class="nav-link" href="">Library</a>
        </li>

        <li class="nav-item dropdown">
            <a class="nav-link" href="">Contact</a>
        </li>

        <li class="nav-item dropdown">
            <a class="nav-link" href="">About</a>
        </li>

        <!-- Social Buttons -->
        <li class="nav-item"><a class="nav-link" href=""><i class="fa fa-facebook mr-1"></i></a></li>
        <li class="nav-item"><a class="nav-link" href=""><i class="fa fa-twitter"></i></a> </li>

    </ul>

    <!-- RIGHT SIDE OF NAVBAR -->
    <ul class="navbar-nav ml-auto">

        <li class="nav-item dropdown m-0">
            {% include "module/_module_search.html" %}
        </li>

        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
                {{ user.username }}
            </a>
            <div class="dropdown-menu">
                <a href="" class="dropdown-item">Profile</a>
                <a class="dropdown-item" href="{% url 'password_change'%}">Change password</a>
            </div>
        </li>

        <li class="nav-item mr-auto">
            <a class="nav-link" href="{% url 'logout' %}">Log Out</a>
        </li>
    </ul>
    {% else %}
    <ul class="navbar-nav ml-auto">
        <li class="nav-item">
            <a class="nav-link" href="{% url 'login' %}">Log In</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'signup' %}">Sign Up</a>
        </li>
    </ul>
    {% endif %}
</nav>
<!-- END NAVIGATION BAR -->